steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '8.12.0'
    displayName: 'Install Node.js'

  - script: |
      npm ci
    displayName: 'Install dependencies'

  - script: |
      npm run build
    displayName: 'Compile'

  - script: |
      npm run package-extension
    displayName: 'package'

  - task: CopyFiles@2
    inputs:
      Contents: '**/*.vsix'
      TargetFolder: '$(Build.ArtifactStagingDirectory)'

  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)'
      ArtifactName: 'drop'
      publishLocation: 'Container'