# Azure Pipelines configuration that builds and packages the extension.
# To learn more about Azure Pipelines: https://aka.ms/learn-azure-pipelines

jobs:
  - job: Windows
    pool:
      vmImage: 'vs2017-win2016'
    steps:
      - template: azure-pipelines-steps.yml
